# .github/workflows/convert.yml
name: AI Singing Voice Conversion

on:
  workflow_dispatch:
    inputs:
      input_mp3:
        description: 'Path to input MP3 file (in repo)'
        required: true
        default: 'input.mp3'
      lyrics_content:
        description: |
          Lyrics block to use for conversion. Example:
          こんな自分に　未来はあるの？
          こんな世界に　私はいるの？
          今切ないの？　今悲しいの？
          自分のことも　解からないまま

          歩むことさえ　疲れるだけよ
          人のことなど　知りもしないわ
          こんな私も　変われるのなら
          もし変われるのなら　白になる
        required: true
        default: |
          こんな自分に　未来はあるの？
          こんな世界に　私はいるの？
          今切ないの？　今悲しいの？
          自分のことも　解からないまま

          歩むことさえ　疲れるだけよ
          人のことなど　知りもしないわ
          こんな私も　変われるのなら
          もし変われるのなら　白になる
      output_mp3:
        description: 'Filename for output MP3'
        required: true
        default: 'converted.mp3'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/svc-develop-team/so-vits-svc.git svc
          pip install -r svc/requirements.txt
          pip install torch soundfile numpy scipy librosa pydub

      - name: Generate lyrics file
        run: |
          echo "${{ github.event.inputs.lyrics_content }}" > lyrics.txt

      - name: Convert MP3 to WAV
        run: |
          python - << 'EOF'
from pydub import AudioSegment
AudioSegment.from_mp3('${{ github.event.inputs.input_mp3 }}').export('input.wav', format='wav')
EOF

      - name: Run singing voice conversion
        run: |
          python svc/inference.py \
            --config svc/config.json \
            --model_path svc/pretrained_model.pth \
            --input input.wav \
            --lyrics lyrics.txt \
            --output output.wav

      - name: Convert WAV back to MP3
        run: |
          python - << 'EOF'
from pydub import AudioSegment
AudioSegment.from_wav('output.wav').export('${{ github.event.inputs.output_mp3 }}', format='mp3')
EOF

      - name: Create GitHub Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: converted-${{ github.run_id }}
          name: Converted Vocal ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MP3 to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.event.inputs.output_mp3 }}
          asset_name: ${{ github.event.inputs.output_mp3 }}
          asset_content_type: audio/mpeg
